//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinoCentar.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KinoCentar.Shared.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navedeni korisnik već je dao odgovor za navedenu anketu!.
        /// </summary>
        public static string anketaKorisnikOdgovor_err {
            get {
                return ResourceManager.GetString("anketaKorisnikOdgovor_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikal sa navedenim imenom već postoji!.
        /// </summary>
        public static string artikal_err {
            get {
                return ResourceManager.GetString("artikal_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo je do greške prilikom generisanja šifre artikla, molimo Vas pokušajte ponovo!.
        /// </summary>
        public static string artikal_sifra_err {
            get {
                return ResourceManager.GetString("artikal_sifra_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film sa navedenim imenom već postoji!.
        /// </summary>
        public static string film_err {
            get {
                return ResourceManager.GetString("film_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filmska ličnost sa navedenim imenom i prezimenom već postoji!.
        /// </summary>
        public static string filmskaLicnost_err {
            get {
                return ResourceManager.GetString("filmskaLicnost_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jedinica mjere sa navedenim imenom već postoji!.
        /// </summary>
        public static string jedinicaMjere_err {
            get {
                return ResourceManager.GetString("jedinicaMjere_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik sa navedenom email adresom već postoji!.
        /// </summary>
        public static string korisnik_email_err {
            get {
                return ResourceManager.GetString("korisnik_email_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik sa navedenim korisničkim imenom već postoji!.
        /// </summary>
        public static string korisnik_err {
            get {
                return ResourceManager.GetString("korisnik_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška prilikom prijave, molimo provjerite Vaše podatke pa pokušajte ponovo!.
        /// </summary>
        public static string login_err {
            get {
                return ResourceManager.GetString("login_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unijeli ste neispravnu lozinku..
        /// </summary>
        public static string login_pass_err {
            get {
                return ResourceManager.GetString("login_pass_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime nije pronađeno ili je vaš nalog neaktivan..
        /// </summary>
        public static string login_user_err {
            get {
                return ResourceManager.GetString("login_user_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrda.
        /// </summary>
        public static string msg_conf {
            get {
                return ResourceManager.GetString("msg_conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška.
        /// </summary>
        public static string msg_err {
            get {
                return ResourceManager.GetString("msg_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poruka o uspjehu.
        /// </summary>
        public static string msg_succ {
            get {
                return ResourceManager.GetString("msg_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozorenje.
        /// </summary>
        public static string msg_war {
            get {
                return ResourceManager.GetString("msg_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brisanje prodaje moguće je samo u roku od 10 min nakon kreiranja!.
        /// </summary>
        public static string prodaja_del_err {
            get {
                return ResourceManager.GetString("prodaja_del_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekcija sa navedenim filmom već postoji za dati period!.
        /// </summary>
        public static string projekcija_err {
            get {
                return ResourceManager.GetString("projekcija_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo je do greške prilikom generisanja broja računa, molimo Vas pokušajte ponovo!.
        /// </summary>
        public static string racun_br_err {
            get {
                return ResourceManager.GetString("racun_br_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navedeni korisnik već ima rezervaciju za navedenu projekciju!.
        /// </summary>
        public static string rezervacija_err {
            get {
                return ResourceManager.GetString("rezervacija_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sala sa navedenim imenom već postoji!.
        /// </summary>
        public static string sala_err {
            get {
                return ResourceManager.GetString("sala_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žanr sa navedenim imenom već postoji!.
        /// </summary>
        public static string zanr_err {
            get {
                return ResourceManager.GetString("zanr_err", resourceCulture);
            }
        }
    }
}
